### ISSUE TITLE
data-tooltip-source functionality described in readme, but not implemented

### ISSUE THREAD

**Issue by mestaritonttu** [scottaohara/a11y_tooltips#2]
Thanks for creating this, it seems like a nice component :)

I tried out the data-tooltip-source thing and wondered why it wasn't working. I examined the source and noticed the code does not know about any tipSourceAttr in reality and has no respective functionality to deal with it.

Maybe you have a local version with this, but did not push it?

**Comment by scottaohara** [comment]
Thanks for the issue @mestaritonttu.

Yah, I removed that feature from the script.  Thought it might be causing an issue I've been dealing with... though that turned out to not be the case.  But after removing it I came to realize it was a feature that really didn't even need to be part of the script in general.  

I've removed the reference to it from the readme.  cheers :)
