### ISSUE TITLE
Should the tooltip hoverable area be increased?

### ISSUE THREAD

**Issue by anevins12** [scottaohara/a11y_tooltips#4]
The following may not be a real scenario as I am not an expert screen magnifier user nor have I dexterity problems.

The problem:
1. When having zoomed into the page with a screen magnifier, longer information in tooltips can become cut off from the viewport
2. When panning to see the full information, if the mouse is moved outside of the tooltip the tooltip can disappear

I appreciate that isn't a WCAG requirement, but I was wondering whether it would be a decent thing to do to help some people out.

I see this problem similar to a standard menu navigation that shows a submenu and the submenu disappears if panning outside of it.

**Comment by scottaohara** [comment]
per our slack convo on this:

...on one hand, this presently meets wcag requirements. on the other, as you demonstrated in your test, for someone with mobility issues / using 400% zoom, it may be difficult to fully see the tooltip when invoked, and they would need to be careful with scrolling it into view / making sure their hover doesn't leave the tooltip area so it doesn't dismiss.

BUT, allowing for a larger tooltip hover area then brings in additional issues of "well, now my mouse is leaving the tooltip area, but it isn't going away, potentially blocking other content from being interacted with and requiring other people, if not those same people, with mobility issues having to move their mouse hover further away from the tooltip than they'd otherwise need to.

to wrap up though, seems a good thing to consider, but also likely somethign that may need to be specifically revised on a project/project basis.
